# Generated by Django 5.1.4 on 2024-12-19 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='書名')),
                ('author', models.CharField(max_length=20, verbose_name='作者')),
                ('isbn', models.CharField(max_length=13, verbose_name='國際標準書號')),
                ('publication_date', models.DateField(verbose_name='出版日期')),
                ('status', models.CharField(choices=[('available', '可借閱'), ('borrowed', '已借出'), ('maintenance', '維護中')], default='available', max_length=20, verbose_name='借閱狀態')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='創建時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
